#!/bin/sh

export O="`pwd`/o"
export TMPDIR=$$

find . -type f -name "test_*" | while read f
do
  "${f}"
  if [ $? -ne 0 ]; then
    echo "${f} failed"
  fi
  rm -rf "${TMPDIR}"
done

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
