#!/bin/sh

export TOP_SRCDIR=`pwd`
export O="${TOP_SRCDIR}/src/o"
export TMPDIR=$$

find . -type f -name "test_*" | while read f
do
  mkdir -p "${TMPDIR}"
  "${f}"
  if [ $? -ne 0 ]; then
    echo "${f} failed"
  fi
  rm -rf "${TMPDIR}"
done

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
