#!/bin/sh

db="${TMPDIR}/db"
${O} create --attr=foo "${db}"
echo -n | ${O} put --attr=foo:bar "${db}"
if [ X"`${O} get --attr=foo "${db}" 0`" != X"bar" ]; then
  exit 1
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
