#!/bin/sh

db="${TMPDIR}/db"
${O} create "${db}"
cat <<EOF | ${O} put "${db}"
foobarbazquuxhogefugapiyo
EOF
if [ X"`${O} search "${db}" foo`" != X"0" ]; then
  exit 1
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
