#!/bin/sh

db="${TMPDIR}/db"
${O} create "${db}"
cat <<EOF | ${O} put "${db}"
foohoge
EOF
cat <<EOF | ${O} put "${db}"
barhoge
EOF
if [ X"`${O} search "${db}" "(foo or bar) and hoge" | sort`" != X"0
1" ]; then
  exit 1
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
