#!/bin/sh

db="${TMPDIR}/db"
${O} create "${db}"
cat <<EOF | ${O} put "${db}"
foobarbazquux
EOF
cat <<EOF | ${O} put "${db}"
hogefugapiyo
EOF
if [ X"`${O} search "${db}" "foo or hoge" | sort`" != X"0
1" ]; then
  exit 1
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
