#!/bin/sh

db="${TMPDIR}/db"
${O} create "${db}"
cat <<EOF | ${O} put "${db}"
中村珠緒がプリキュアを脱退した。
EOF
if [ X"`${O} search --fuzzy "${db}" モーニング娘を脱退`" != X"" ]; then
  exit 1
fi

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
