--- !ditz.rubyforge.org,2008-03-06/project 
name: o
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-05-16 18:04:29.769113 Z
    - SumiTomohiko <SumiTomohiko@neko-daisuki.ddo.jp>
    - created
    - This version implements ambiguous search.
